package fit.iuh.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Response DTO for the holistic resume assessment API.
 *
 * <p>Returned by both the blocking ({@code GET /api/v2/assess-resume}) endpoint.
 * Contains the full Markdown report plus extracted metadata for quick dashboard rendering.
 */
@Data
@Builder
public class AssessmentResponse {

    /** UUID of the persisted {@code ResumeAssessment} database record. */
    @JsonProperty("id")
    private UUID id;

    /** The interview session this assessment belongs to. */
    @JsonProperty("sessionId")
    private String sessionId;

    /**
     * Overall match score (0-100) extracted from the LLM report.
     * Null if the LLM did not produce a parseable score.
     */
    @JsonProperty("overallScore")
    private Integer overallScore;

    /**
     * Hiring recommendation extracted from the LLM report.
     * One of: "Strong Fit", "Good Fit", "Partial Fit", "Poor Fit".
     */
    @JsonProperty("hiringRecommendation")
    private String hiringRecommendation;

    /** The complete assessment report in Markdown format. */
    @JsonProperty("report")
    private String report;

    /**
     * Whether this result was served from the database cache (true)
     * or freshly generated by the LLM (false).
     */
    @JsonProperty("cached")
    private boolean cached;

    /** Timestamp when the assessment was first persisted. */
    @JsonProperty("createdAt")
    private LocalDateTime createdAt;
}
