package fit.iuh.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * API Response DTO for the SimInterview resume assessment endpoint.
 *
 * <p>Exposes the 3 core SimInterview outputs alongside session metadata and cache status.
 * Returned by {@code GET /api/v2/assess-resume?sessionId={id}}.
 *
 * <h3>Field Mapping from Entity</h3>
 * <pre>
 *   ResumeAssessment.competencyFitScore    → competencyFitScore
 *   ResumeAssessment.sectionWiseFeedback   → sectionWiseFeedback
 *   ResumeAssessment.actionableSuggestions → actionableImprovementSuggestions
 * </pre>
 */
@Data
@Builder
public class AssessmentResponse {

    /** UUID of the persisted {@code ResumeAssessment} database record. */
    @JsonProperty("id")
    private UUID id;

    /** The interview session this assessment belongs to. */
    @JsonProperty("session_id")
    private String sessionId;

    // -------------------------------------------------------------------------
    // SimInterview Output 1
    // -------------------------------------------------------------------------

    /**
     * Competency-level fit score (0–100) representing the overall alignment
     * between the candidate's competencies and the JD requirements.
     */
    @JsonProperty("competency_fit_score")
    private Integer competencyFitScore;

    // -------------------------------------------------------------------------
    // SimInterview Output 2
    // -------------------------------------------------------------------------

    /**
     * Structured section-wise feedback containing skill, experience, and project
     * evaluations. The nested {@code critical_missing_skills} is key input for
     * Module 3 (Question Bank Generation).
     */
    @JsonProperty("section_wise_feedback")
    private AssessmentResponseDto.SectionWiseFeedback sectionWiseFeedback;

    // -------------------------------------------------------------------------
    // SimInterview Output 3
    // -------------------------------------------------------------------------

    /**
     * Ordered list of actionable improvement suggestions the candidate can
     * immediately act on to increase their fit for this role.
     */
    @JsonProperty("actionable_improvement_suggestions")
    private List<String> actionableImprovementSuggestions;

    // -------------------------------------------------------------------------
    // Metadata
    // -------------------------------------------------------------------------

    /**
     * Whether this result was served from the database cache ({@code true})
     * or freshly generated by the LLM ({@code false}).
     * Useful for clients to display a "cached result" badge.
     */
    @JsonProperty("cached")
    private boolean cached;

    /** Timestamp when the assessment was first persisted to the database. */
    @JsonProperty("created_at")
    private LocalDateTime createdAt;
}
