spring:
  application:
    name: ai-inference-service
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      base-url: ${LLM_API_URL:https://openrouter.ai/api/v1}
      api-key: ${LLM_API_KEY}
      chat:
        options:
          model: ${LLM_MODEL:google/gemini-2.5-flash}
          headers:
            HTTP-Referer: "https://github.com/nguyenhoangkhq7/smile-interview"
            X-Title: "Smile Interview App"
grpc:
  server:
    port: 9091
