package fit.iuh.modules.chunking;

import fit.iuh.modules.chunking.entity.DocumentChunk;
import fit.iuh.modules.chunking.repository.DocumentChunkRepository;
import fit.iuh.modules.chunking.service.EmbeddingService;
import fit.iuh.modules.chunking.service.RetrievalService;
import fit.iuh.modules.chunking.service.impl.RetrievalServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;

class RetrievalServiceTest {

    private DocumentChunkRepository repository;
    private EmbeddingService embeddingService;
    private RetrievalService retrievalService;

    @BeforeEach
    void setUp() {
        repository = Mockito.mock(DocumentChunkRepository.class);
        embeddingService = Mockito.mock(EmbeddingService.class);
        retrievalService = new RetrievalServiceImpl(repository, embeddingService);
    }

    @Test
    @DisplayName("Hybrid search combines Dense and Sparse results using RRF fusion")
    void testHybridSearchWithRrf() {
        UUID id1 = UUID.randomUUID();
        UUID id2 = UUID.randomUUID();

        DocumentChunk chunk1 = DocumentChunk.builder()
                .id(id1)
                .sessionId("session-1")
                .docType("cv")
                .content("Original text chunk 1 for Redis and caching")
                .enrichedContent("Enriched context line. Original text chunk 1 for Redis and caching")
                .build();

        DocumentChunk chunk2 = DocumentChunk.builder()
                .id(id2)
                .sessionId("session-1")
                .docType("cv")
                .content("Original text chunk 2 for Spring Boot microservices")
                .enrichedContent("Enriched context line. Original text chunk 2 for Spring Boot microservices")
                .build();

        when(embeddingService.embedQuery(anyString())).thenReturn(new float[1024]);
        when(repository.searchDense(anyString(), anyString(), anyString(), anyInt())).thenReturn(List.of(chunk1, chunk2));
        when(repository.searchSparse(anyString(), anyString(), anyString(), anyInt())).thenReturn(List.of(chunk2, chunk1));

        List<DocumentChunk> results = retrievalService.retrieveRelevantChunks("session-1", "cv", "Redis", 2);

        assertNotNull(results);
        assertEquals(2, results.size());
    }

    @Test
    @DisplayName("STRICT SAFEGUARD: retrieveRelevantCvContext ONLY uses original content, NEVER enrichedContent")
    void testSafeguardUsesOriginalContentOnly() {
        UUID parentId = UUID.randomUUID();
        UUID childId = UUID.randomUUID();

        DocumentChunk parentChunk = DocumentChunk.builder()
                .id(parentId)
                .sessionId("session-1")
                .docType("cv")
                .chunkType("project_overview")
                .content("Parent Project Original Text")
                .enrichedContent("DO NOT USE THIS ENRICHED PARENT TEXT")
                .build();

        DocumentChunk childChunk = DocumentChunk.builder()
                .id(childId)
                .sessionId("session-1")
                .docType("cv")
                .parentId(parentId)
                .chunkType("domain_child")
                .content("Child Original Text for JWT Security")
                .enrichedContent("DO NOT USE THIS ENRICHED CHILD TEXT GENERATED BY 3B MODEL")
                .build();

        when(repository.existsBySessionId("session-1")).thenReturn(true);
        when(embeddingService.embedQuery(anyString())).thenReturn(new float[1024]);
        when(repository.searchDense(anyString(), anyString(), anyString(), anyInt())).thenReturn(List.of(childChunk));
        when(repository.searchSparse(anyString(), anyString(), anyString(), anyInt())).thenReturn(List.of(childChunk));
        when(repository.findAllById(anySet())).thenReturn(List.of(parentChunk));

        String retrievedContext = retrievalService.retrieveRelevantCvContext("session-1", List.of("JWT Security"), 5);

        assertNotNull(retrievedContext);
        assertTrue(retrievedContext.contains("Parent Project Original Text"));
        assertTrue(retrievedContext.contains("Child Original Text for JWT Security"));
        assertFalse(retrievedContext.contains("DO NOT USE THIS ENRICHED"), "MUST NOT contain enriched_content in retrieved prompt snippet");
    }
}
