package fit.iuh.modules.assessment;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * API Response DTO for the SimInterview resume assessment endpoint.
 *
 * <p>Exposes the refactored assessment outputs: ENUM-typed metadata, Java-computed score,
 * and LLM-extracted evidence items. Returned by {@code GET /api/v2/assess-resume?sessionId=X}.
 *
 * <h3>Score Transparency</h3>
 * {@code overallMatchScore} is clearly labelled as Java-computed (not LLM-generated)
 * to maintain trust and auditability in the response.
 */
@Data
@Builder
public class AssessmentResponse {

    /** UUID of the persisted {@code ResumeAssessment} database record. */
    @JsonProperty("id")
    private UUID id;

    /** The interview session this assessment belongs to. */
    @JsonProperty("session_id")
    private String sessionId;

    // -------------------------------------------------------------------------
    // Metadata — from MetadataExtractionService (ENUM-typed)
    // -------------------------------------------------------------------------

    /**
     * Engineering domain of the JD (e.g., "BACKEND", "DEVOPS").
     * Mapped from {@link JobCategory} ENUM — type-safe, not a free string.
     */
    @JsonProperty("job_category")
    private JobCategory jobCategory;

    /**
     * Required seniority level from the JD (e.g., "FRESHER", "MID").
     * Mapped from {@link SeniorityLevel} ENUM — type-safe, not a free string.
     */
    @JsonProperty("seniority_level")
    private SeniorityLevel seniorityLevel;

    // -------------------------------------------------------------------------
    // Score — computed by Java ScoringService
    // -------------------------------------------------------------------------

    /**
     * Overall CV-JD match score (0–100) calculated by {@link ScoringService}.
     * <strong>This value is NOT generated by the LLM.</strong>
     * It is computed from the weighted evidence items using the formula:
     * {@code SUM(weight_i * points_i) / SUM(weight_i) * 100}.
     */
    @JsonProperty("overall_match_score")
    private Integer overallMatchScore;

    // -------------------------------------------------------------------------
    // Evidence — from LLM (evidence-matching engine output)
    // -------------------------------------------------------------------------

    /**
     * Flat list of evidence items, one per evaluation criterion.
     * Each item contains the criterion name, JD requirement, CV evidence, and match status.
     * Populated by the LLM; scores are NOT included here.
     */
    @JsonProperty("evidence_items")
    private List<AssessmentResponseDto.EvidenceItem> evidenceItems;

    /**
     * Ordered list of actionable improvement suggestions from the LLM.
     */
    @JsonProperty("top_priority_improvements")
    private List<String> topPriorityImprovements;

    // -------------------------------------------------------------------------
    // Cache metadata
    // -------------------------------------------------------------------------

    /**
     * Whether this result was served from the DB cache ({@code true})
     * or freshly generated ({@code false}).
     */
    @JsonProperty("cached")
    private boolean cached;

    /** Timestamp when the assessment was first persisted to the database. */
    @JsonProperty("created_at")
    private LocalDateTime createdAt;
}
